/**
 * Enum for authentication service error codes
 */
export enum AuthServiceErrorCode {
    // Login/credentials errors
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
    
    // Token errors
    REFRESH_TOKEN_REQUIRED = 'REFRESH_TOKEN_REQUIRED',
    INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
    
    // Password errors
    CURRENT_PASSWORD_REQUIRED = 'CURRENT_PASSWORD_REQUIRED',
    NEW_PASSWORD_REQUIRED = 'NEW_PASSWORD_REQUIRED',
    PASSWORDS_MATCH = 'PASSWORDS_MATCH',
    CURRENT_PASSWORD_INCORRECT = 'CURRENT_PASSWORD_INCORRECT',
    
    // Reset password errors
    RESET_TOKEN_REQUIRED = 'RESET_TOKEN_REQUIRED',
    INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',

    // Registration errors
    USERNAME_EXISTS = 'USERNAME_EXISTS',
    EMAIL_EXISTS = 'EMAIL_EXISTS',
    DEFAULT_ROLE_NOT_FOUND = 'DEFAULT_ROLE_NOT_FOUND',
    
    // User errors
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    EMAIL_REQUIRED = 'EMAIL_REQUIRED'
}